### ISSUE TITLE
Admin tool for updating database through file

### ISSUE THREAD

**Issue by Roger-Chavez** [fast-food-finder-associates/FastFoodFinder#10]
As an admin I’d like to be able to load the database through a file so that I can mass update the database.

### Tasks:
* In the admin tool UI, add a way to prompt this action
* Prompt a `QFileDialog` for the file
* Be ready to catch file format exception classes
* Handle exceptions properly
* Inform the admin of any events

### Tests:
* Parse an empty file (throw exception)
* Parse a file with `1` correct restaurant
* Parse a file with `5` correct restaurants
* Parse a file with `1` correct and `1` incorrect restaurants (throw exception)
* Parse a file with `1` incorrect restaurant (throw exception)

### Definition of done:
* The program instantiates objects of restaurants and menu items and populates our programs main data structure so that we can connect the object to the font end and allow our users to interact with the data. 

**Priority:** High

**Comment by ChrisRzech** [comment]
@edtyler55 you mentioned that issue #14 should handle just the UI portion because the backend handled the rest. Would you say the same about this issue?

**Comment by ChrisRzech** [comment]
Will add definition of done after some details are cleared up

**Comment by edtyler55** [comment]
Yes. I updated the google docs and test plan last night to reflect this.

**Comment by ChrisRzech** [comment]
Somewhat of a duplicate by #22. The only difference of this one is deleting the current database and using the data from the file (which won't be done anymore).
