### ISSUE TITLE
Admin tool for saving current database to a file

### ISSUE THREAD

**Issue by ChrisRzech** [fast-food-finder-associates/FastFoodFinder#14]
As an admin, I want to be able to save the current database to a file so that changes between program executions are consistent.

### Tasks:
* Once the program is closed, prompt the backend to save all data into databases

### Tests:
* Save an empty database
* Save a database with `1` object
* Save a database with `10` objects

### Definition of done:
* When the program is finished, all changes are saved and can be seen again the next time the program is used

**Priority:** Low

**Comment by AAE1997** [comment]
What format do you want the data to be saved as? .txt file?

**Comment by ChrisRzech** [comment]
I would opt  for a custom file extension name: `database.fff`

**Comment by Roger-Chavez** [comment]
really? Why?

**Comment by ChrisRzech** [comment]
Just for the fun of it, seeing a `.txt` doesn't make much impression.

**Comment by ChrisRzech** [comment]
Plus, it would allow whoever to easily distinguish what kind of file it is. That's kind of the reason why file extensions exist.

**Comment by ChrisRzech** [comment]
And in addition, whenever we allow loading database files, we can make the `QFileDialog` only see `.fff` files or whatever extension name we use.

**Comment by Roger-Chavez** [comment]
If this were _Kaths_ class maybe, but I wouldn't try anything fancy with **Lebowitz**. If he gave us `.txt` to work with I'm going to guess that's what he'll be looking for.

**Comment by ChrisRzech** [comment]
Fine by me, just thought it would look better.

**Comment by edtyler55** [comment]
The data store back end will supply a method to serialize the database
to a specified file path. Task #14 describes, in my view, the UI front
end to this method and not the actual file i/o.

Note that that this task has been changed to write backup files only
and not to write the file that is actually the backing store, which is
done automatically whenever a change is made to the data store
objects.

Eugene

**Comment by ChrisRzech** [comment]
Agreed, I will update the story to handle the UI
