### ISSUE TITLE
Contact us widget

### ISSUE THREAD

**Issue by ChrisRzech** [fast-food-finder-associates/FastFoodFinder#15]
As a client, I want to be able to contact the developer team so that I can inform them of bugs or errors in the program.

### Tasks:
* Create a class called `ContactUs` that inherits `QDialog`
* In the default constructor, set the window flags to the following
```cpp
    setWindowFlags(Qt::MSWindowsFixedSizeDialogHint |
                   Qt::WindowSystemMenuHint |
                   Qt::WindowMinimizeButtonHint |
                   Qt::WindowCloseButtonHint);
```
* Design the `.ui` file to display the developer team's contact information
* Add the developer team's contact information
* Add the company logo to the window
* Add a button to the `mainwindow.ui`'s menu bar for opening this window
* The button should be under a section named `About` or something similar
* Make `MainWindow` have a class member to instantiate a `ContactUs` object
* In `MainWindow`, create a private slot for the button
* In the slot, do the following functions on the `ContactUs` object
```cpp
    setModal(true);
    exec();
```

### Tests:
* Open the window using the button in the menu bar
* Confirm that the developer team's contact information is shown
* Confirm that the company logo is shown

### Definition of done:
* A window that holds information about the team can be shown at a click of a button

**Priority:** Lowest

**Comment by AAE1997** [comment]
Can you provide a clear description of #15 please?

**Comment by AAE1997** [comment]
Can you please provide a clear description of #15 please?

**Comment by Roger-Chavez** [comment]
@AAE1997 Chris is working on a clear description, just a sec

**Comment by ChrisRzech** [comment]
@AAE1997 the story is now fully updated

**Comment by dacruz21** [comment]
@AAE1997 LOL

**Comment by AAE1997** [comment]
Is QDialog finished or is being developed?

**Comment by ChrisRzech** [comment]
No, it is a class in Qt

**Comment by ChrisRzech** [comment]
Updated the story a little

**Comment by dacruz21** [comment]
@AAE1997 ?????????

**Comment by typokign** [comment]
happy to help review : )

**Comment by Roger-Chavez** [comment]
> Is QDialog finished or is being developed?

https://doc.qt.io/qt-5/qdialog.html

**Comment by AAE1997** [comment]
I'm still working on QDialog. Development is still in progress.

**Comment by ChrisRzech** [comment]
Didn't finish within project due date, closing.
