### ISSUE TITLE
Add Stacks in Mission Viejo

### ISSUE THREAD

**Issue by typokign** [fast-food-finder-associates/FastFoodFinder#36]
As a Chris, I want to be able to locate the restaurant Stacks, in Mission Viejo, so that I can get pancakes with my buds. :)

### Tasks:
* Add Stacks to restaurant database

### Tests:
* Test that the restaurant appears in the app
* Make sure that the bug where the Chris becomes unresponsive when asked about Stacks, is resolved.

### Definition of done:
* Chris successfully meets at Stacks and enjoys his breakfast

**Priority:** Highest

**Comment by ChrisRzech** [comment]
![image](https://user-images.githubusercontent.com/5513122/54650254-d14d3e80-4a6a-11e9-8644-46ebc2f7f3f7.png)
 https://www.youtube.com/watch?v=wXt_BBpdzok
